### ISSUE TITLE
Jax-ws client requires WSDL file at runtime ?

### ISSUE THREAD

**Issue by DoneSpeak** [mojohaus/jaxws-maven-plugin#87]
Has the following problem been solved which I copy from [Jax-ws client requires WSDL file at runtime ?](http://metro.1045641.n5.nabble.com/Jax-ws-client-requires-WSDL-file-at-runtime-td1061628.html) and bothering me a lot.

----
I generated client and server code for my wsdl using wsimport.

However the client code on startup is looking for the WSDL file in the location it existed in on the machine where I ran wsimport. I would imagine that with all the annotations in the generated code the client should not require the .wsdl at runtime ?

The problem is, when I take the standalone client code and distribute it to other machines, the client fails with the "Failed to access WSDL file exception".

Exception in thread "AWT-EventQueue-0" javax.xml.ws.WebServiceException: Failed to access the WSDL at: file:/C:/BackendManagerForGUI.wsdl. It failed with:
        /C:/BackendManagerForGUI.wsdl (No such file or directory).
        at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.tryWithMex(RuntimeWSDLParser.java:162)
        at com.sun.xml.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:144)
        at com.sun.xml.ws.client.WSServiceDelegate.parseWSDL(WSServiceDelegate.java:254)
        at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:217)
        at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:174)
        at com.sun.xml.ws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:104)
        at javax.xml.ws.Service.<init>(Service.java:56)

I am creating a proxy using code that looks like:

                BackendManagerService bm = new BackendManagerService();
               
                port = bm.getBackendManagerPort();

                // Use Proxy Instance as BindingProvider
                BindingProvider bp = (BindingProvider) port;

                Map<String, Object> rc = bp.getRequestContext();
                rc.put (BindingProvider.ENDPOINT_ADDRESS_PROPERTY,
                "http://localhost:9077/BackManager");

Is there some other way for me to create the client service so that it does not require the .wsdl file at runtime ?

**Comment by andham** [comment]
This mojo is just a wrapper around the JAX-WS toolset, so what you're asking about is about the classes generated by that tool (wsimport).
Having said that I solved this by including the wsdl in the jar and make the generated ws client use it during runtime by providing this mojo execution configuration:
```
    <configuration>
        <packageName>com.acme.foo.wsclient</packageName>
        <wsdlDirectory>${project.basedir}/src/main/resources</wsdlDirectory>
        <wsdlFiles>
            <wsdlFile>com/acme/foo/wsclient/BarService.wsdl</wsdlFile>
        </wsdlFiles>
        <wsdlLocation>BarService.wsdl</wsdlLocation>
        <xuseBaseResourceAndURLToLoadWSDL>true</xuseBaseResourceAndURLToLoadWSDL>
    </configuration>
```
The trick here is the combination of xuseBaseResourceAndURLToLoadWSDL and wsdlLocation. Do note that the wsdl file needs to be in the package path of the generated client.

**Comment by ShadowM0nkey** [comment]
Have this same problem but only when I try moving from Java 8 to Java 17. Client works when we're on Java 8 using version 2.6 of jaxws-maven-plugin but when I try to run the same code on a JDK17 build it fails with the above error. Is it possible 2.6 isn't compatible with 17 and JakartaEE 8.0?

**Comment by dmatej** [comment]
> Have this same problem but only when I try moving from Java 8 to Java 17. Client works when we're on Java 8 using version 2.6 of jaxws-maven-plugin but when I try to run the same code on a JDK17 build it fails with the above error. Is it possible 2.6 isn't compatible with 17 and JakartaEE 8.0?

Jakarta EE 8 and 9 was compatible with Java 8
Jakarta EE 9.1 with 11
Jakarta EE 10 with 11-17
Jakarta EE 11 with 17-21 (should be released this year) 

I think you can mess a bit with dependencies of the plugin, but it is bit risky, you should always test the result (if it compiles). You can also try to switch again to [Jakarta EE plugin](https://eclipse-ee4j.github.io/metro-jax-ws/jaxws-maven-plugin/).
I am not using SOAP services now, I remember both had some pros and cons.
