### ISSUE TITLE
Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "main"

### ISSUE THREAD

**Issue by tillias** [mojohaus/jaxws-maven-plugin#88]
Hello folks,

I'm trying to generate sample async client for ws. Here is src https://github.com/tillias/reactive-ws

When bindingFiles is specified it fails with 

`
[INFO] --- jaxws-maven-plugin:2.6:wsimport (default) @ asyncws ---
[INFO] Processing: file:/C:/Development/Projects/asyncws/src/wsdl/CountryInfoService.wsdl
[INFO] jaxws:wsimport args: [-keep, -s, 'C:\Development\Projects\asyncws\target\generated-sources\wsimport', -d, 'C:\Development\Projects\asyncws\target\classes', -encoding, UTF-8, -extension, -Xnocompile, -p, com.example.asyncws.client, -wsdllocation, /wsdl/CountryInfoService.wsdl, -b, 'file:/C:/Development/Projects/asyncws/src/resources/bindings.xml', "file:/C:/Development/Projects/asyncws/src/wsdl/CountryInfoService.wsdl"]
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.mojo.jaxws.Invoker.main(Invoker.java:80)
`
I have also asked on https://stackoverflow.com/questions/63886421/jaxws-maven-plugin2-6-invocation-of-com-sun-tools-ws-wscompile-wsimporttool-fai

Please advise.

**Comment by robota666** [comment]
Hello,
I know this is an old question, but I'm just having the same issue, and with the hint "When bindingFiles is specified" from @tillias  question I found out that the path to my binding file had a typo. Fixing the typo made the problem went away. Hope this comment will help others getting around this otherwise meaning nothing error message.
PS: the stackoverflow link doesn't work any more.
